# Generated by Django 5.0 on 2023-12-12 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeEssay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=255, verbose_name='College Name')),
                ('major', models.CharField(max_length=100, verbose_name='Intended Major')),
                ('original_essay_title', models.CharField(max_length=255, verbose_name='Original Essay Title')),
                ('original_essay_content', models.TextField(verbose_name='Original Essay Content')),
                ('improved_essay_title', models.CharField(max_length=255, verbose_name='Improved Essay Title')),
                ('improved_essay_content', models.TextField(verbose_name='Improved Essay Content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'College Essays',
            },
        ),
    ]
