# Generated by Django 5.0 on 2023-12-13 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essay', '0002_collegeessay_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collegeessay',
            name='improved_essay_content',
        ),
        migrations.RemoveField(
            model_name='collegeessay',
            name='status',
        ),
        migrations.AddField(
            model_name='collegeessay',
            name='additional_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Additional Notes'),
        ),
        migrations.AlterField(
            model_name='collegeessay',
            name='improved_essay_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Improved Essay Title'),
        ),
    ]
